<?php
/**
 * Implements hook_pane_plugins
 *
 * @return array
 */
function pane_entity_reference_pane_plugins() {
  $plugins = array();

  $plugins['pane_entity_reference'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'pane_entity_reference') . '/plugins/panes',
      'file' => 'pane_entity_reference.inc',
      'class' => 'pane_entity_reference',
      'parent' => 'pane_base',
    ),
  );

  return $plugins;
}

function pane_entity_reference_pane_registry() {
  $registry = array();

  $registry['entity_reference'] = array(
    'title' => t('Entity reference'),
    'description' => t('Entity reference'),
    'plugin' => 'pane_entity_reference',
  );

  return $registry;
}